# feign read timeout
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=10000

  # feign read timeout disable
hystrix.command.default.execution.timeout.enabled=false

feign.compression.request.enabled=true
feign.compression.response.enabled=true
feign.compression.request.mime-types=application/json
feign.hystrix.enabled=false